name = "Rage Border"
author = "Grey Cat"
version = "2.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47c6a5cb15960ec39a22725e906a4fd27bd39665db9d1292f96ddcaa8131eb47"

[versions]
fabric = "0.16.14"
minecraft = "1.19.4"
