name = "Rage Border"
author = "Grey Cat"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb3e9344e27993eeccb4e667640d1aaba1e4b9cc3c91ec1c7fde8e097b8ebfe4"

[versions]
fabric = "0.16.14"
minecraft = "1.19.4"
